FROM python:2-slim

RUN apt-get update && apt-get install -y \
	gcc \
	libxml2 \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY main.py ./main.py

EXPOSE 5000

CMD [ "python", "main.py" ]
